package:
  name: ourotools
  version: 0.2.1

build:
  number: 1

requirements:
  run:
    - python
about:
  summary: A comprehensive toolkit for quality control and analysis of single-cell long-read RNA-seq data
